### ISSUE TITLE
Feature - Song Title Fully Relayed by the Bot

### ISSUE THREAD

**Issue by madewise** [CSC510-Team-Wise-Vilkomir-Sykes/Enigma#16]
Upon requesting a song be played by the bot, the bot will process the song request and relay the exact YouTube video title instead of what the user has typed in. This solves some confusion of casual language that users may use in Discord servers. For example, upon inviting the bot to the voice channel and providing it the commands "/queue our lawyer made us change" and "/next" - indicating the user likely wants the bot to play the Fall Out Boy song "Our Lawyer Made Us Change The Name Of This Song So We Wouldn't Get Sued," but left out the remainder of the title for convenience in typing the command. Instead of the bot relaying "Now playing: our lawyer made us change," the bot would relay the exact title of the YouTube video, including the full name of the song (Now playing: Our Lawyer Made Us Change The Name Of This Song So We Wouldn't Get Sued). This ensures anyone who isn't in the voice channel can know exactly what songs are currently playing, if they are interested in joining.

**Comment by ScenicJaguar101** [comment]
Note: this is an extra feature and is meant for the next team to finish

**Comment by ScenicJaguar101** [comment]
Closing for grading
